import { type NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const { action, data } = await request.json()

    if (action === "send-email") {
      return await sendEmail(data)
    } else {
      return NextResponse.json({ error: "Invalid action" }, { status: 400 })
    }
  } catch (error) {
    console.error("Error in IdeaHub V2 API:", error)
    return NextResponse.json({ error: error instanceof Error ? error.message : "Unknown error" }, { status: 500 })
  }
}

async function sendEmail(data: { to: string; name: string; content: string; imageUrl: string }) {
  try {
    console.log("Sending IdeaHub V2 email via Resend to:", data.to)

    const response = await resend.emails.send({
      from: "IdeaHub AI V2 - The Next Level U <noreply@marketing.thenextlevelu.com>",
      to: [data.to],
      subject: "Your AI-Generated Content V2 - Enhanced with Professional Photography",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #7c3aed, #2563eb); padding: 20px; text-align: center;">
            <h1 style="color: white; margin: 0;">Your Enhanced Content is Ready!</h1>
            <p style="color: white; margin: 10px 0 0 0;">Generated by IdeaHub AI V2 - The Next Level U</p>
            <span style="background: rgba(255,255,255,0.2); color: white; padding: 4px 8px; border-radius: 12px; font-size: 12px; margin-top: 8px; display: inline-block;">BETA</span>
          </div>
          
          <div style="padding: 30px; background: #f9fafb;">
            <h2 style="color: #1f2937; margin-bottom: 20px;">Hi ${data.name},</h2>
            
            <p style="color: #4b5563; line-height: 1.6;">
              Your AI-generated social media content is ready with enhanced professional photography! This version uses high-quality stock images with Century 21 branding for a more polished look.
            </p>
            
            <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #7c3aed;">
              <h3 style="color: #1f2937; margin-top: 0;">Your Social Media Post:</h3>
              <p style="color: #4b5563; line-height: 1.6; white-space: pre-wrap;">${data.content}</p>
            </div>
            
            <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; text-align: center;">
              <h3 style="color: #1f2937; margin-top: 0;">Your Professional Image:</h3>
              <img src="${data.imageUrl}" alt="Professional real estate content image" style="max-width: 100%; height: auto; border-radius: 8px;" />
            </div>
            
            <p style="color: #4b5563; line-height: 1.6;">
              This enhanced version features professional stock photography that's been optimized for social media engagement. You can use both the text and image for your posts on Facebook, LinkedIn, Instagram, and other platforms.
            </p>
            
            <div style="background: #e0f2fe; padding: 15px; border-radius: 8px; margin: 20px 0;">
              <p style="color: #0277bd; margin: 0; font-size: 14px;">
                <strong>✨ What's New in V2:</strong><br>
                • Professional stock photography from Unsplash<br>
                • Enhanced image quality and composition<br>
                • Better social media optimization<br>
                • Consistent Century 21 branding
              </p>
            </div>
            
            <p style="color: #6b7280; font-size: 14px; line-height: 1.6;">
              Best regards,<br>
              The Next Level U Team<br>
              <a href="mailto:MikePuma@c21be.com" style="color: #7c3aed;">MikePuma@c21be.com</a>
            </p>
          </div>
          
          <div style="background: #1f2937; padding: 20px; text-align: center;">
            <p style="color: #9ca3af; margin: 0; font-size: 14px;">
              © 2024 The Next Level U. Empowering real estate professionals with AI-powered tools.
            </p>
          </div>
        </div>
      `,
    })

    if (response.error) {
      console.error("Resend error:", response.error)
      throw new Error(`Failed to send email: ${response.error.message}`)
    }

    console.log("IdeaHub V2 email sent successfully:", response.data?.id)
    return NextResponse.json({ success: true, messageId: response.data?.id })
  } catch (error) {
    console.error("Error sending IdeaHub V2 email:", error)
    throw new Error(`Failed to send email: ${error instanceof Error ? error.message : "Unknown error"}`)
  }
}
