import { type NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const data = await request.json()
    const { to, name, plan, html } = data

    console.log("Action plan email API route called with data:", { to, name })

    const { data: emailData, error } = await resend.emails.send({
      from: "Mike Puma - The Next Level U <noreply@marketing.thenextlevelu.com>",
      to: [to],
      subject: `Your Daily Action Plan - ${new Date().toLocaleDateString()}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
          <div style="background: linear-gradient(135deg, #4338ca, #3b82f6); padding: 30px; text-align: center;">
            <h1 style="color: white; margin: 0; font-size: 28px;">Your Daily Action Plan</h1>
            <p style="color: white; margin: 15px 0 0 0; font-size: 16px;">Generated by Action AI - The Next Level U</p>
          </div>
          
          <div style="padding: 30px; background: #f9fafb;">
            <h2 style="color: #1f2937; margin-bottom: 20px; font-size: 24px;">Hi ${name},</h2>
            
            <p style="color: #4b5563; line-height: 1.6; font-size: 16px;">
              Your daily action plan is ready! This plan is designed to help you effectively prospect 
              and connect with your target audience today.
            </p>
            
            <div style="background: #f0f9ff; padding: 15px; border-radius: 8px; margin: 25px 0; border-left: 4px solid #b6a888;">
              <h4 style="color: #1e3a8a; margin: 0 0 10px 0; font-size: 16px;">Today's Prospecting Focus:</h4>
              <p style="color: #1e40af; margin: 0; font-size: 15px;">${data.plan.split("🔍 Prospecting Focus")[1]?.split("📱")[0]?.trim() || "Your specified target audience"}</p>
            </div>
            
            <p style="color: #4b5563; line-height: 1.6; font-size: 16px;">
              I've attached your complete action plan with scripts for texts, calls, and emails. 
              Execute this plan today to maximize your prospecting effectiveness.
            </p>

            <div style="background: linear-gradient(135deg, #fef3c7, #fde68a); padding: 20px; border-radius: 8px; margin: 25px 0; border: 1px solid #f59e0b;">
              <h4 style="color: #92400e; margin: 0 0 15px 0; font-size: 16px;">💡 Tips for Success:</h4>
              <ul style="color: #78350f; margin: 0; padding-left: 20px; line-height: 1.6;">
                <li style="margin-bottom: 5px;">Schedule specific time blocks for each activity</li>
                <li style="margin-bottom: 5px;">Track your results to refine your approach</li>
                <li style="margin-bottom: 5px;">Personalize the scripts for each prospect</li>
                <li style="margin-bottom: 5px;">Follow up consistently with interested leads</li>
                <li>Create a new action plan tomorrow to maintain momentum</li>
              </ul>
            </div>
            
            <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin-top: 30px;">
              Best regards,<br>
              <strong>Mike Puma</strong><br>
              The Next Level U Team<br>
              <a href="mailto:MikePuma@c21be.com" style="color: #4338ca; text-decoration: none;">MikePuma@c21be.com</a>
            </p>
          </div>
          
          <div style="background: #1f2937; padding: 25px; text-align: center;">
            <p style="color: #9ca3af; margin: 0; font-size: 14px;">
              © 2024 The Next Level U. Empowering real estate professionals with AI-powered tools.
            </p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: `Daily_Action_Plan_${new Date().toLocaleDateString().replace(/\//g, "-")}.html`,
          content: html,
        },
      ],
    })

    if (error) {
      console.error("Resend error:", error)
      throw new Error(`Resend error: ${error.message}`)
    }

    console.log("Action plan email sent successfully:", emailData?.id)
    return NextResponse.json({ success: true, messageId: emailData?.id })
  } catch (error) {
    console.error("Error in action plan email API route:", error)
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
        details: error instanceof Error ? error.stack : undefined,
      },
      { status: 500 },
    )
  }
}
