"use client"

const topicOptions = [
  "The benefits of working with a real estate agent",
  "How to prepare your home for sale",
  "The process of buying a new home",
  "The importance of home inspections",
  "Tips for first-time home buyers",
  "How to stage your home for maximum appeal",
  "The benefits of owning a vacation home",
  "How to find the perfect neighborhood for your family",
  "The pros and cons of renting vs. buying",
  "How to negotiate a better deal on a home",
  "How to finance a new home",
  "How to find the best mortgage rates",
  "How to maintain and improve your credit score",
  "How to invest in real estate",
  "How to flip a house for profit",
  "How to find the best real estate deals",
  "How to make money in real estate",
  "How to create a budget for buying a new home",
  "How to handle closing costs",
  "How to find the right property management company",
  "How to choose the right home insurance",
  "How to create a home maintenance schedule",
  "How to find the best home warranty plan",
  "How to create a home security plan",
  "How to create a home automation system",
  "How to design a sustainable home",
  "How to find the best architect or designer for your home",
  "How to find the best contractor for your home renovation",
  "How to create a home office space",
  "How to create a home gym",
  "How to create a home theater",
  "How to create an outdoor living space",
  "How to create a home garden",
  "How to create a home pool or spa",
  "How to create a home wine cellar or tasting room",
  "How to create a home library or study",
  "How to create a home spa or massage room",
  "How to create a home sauna or steam room",
  "How to create a home game room or arcade",
  "How to create a home bar or lounge",
  "How to create a home pet grooming room",
  "How to create a home yoga or meditation room",
  "How to create a home greenhouse or sunroom",
  "How to create a home artist studio",
  "How to create a home dance studio",
  "How to create a home music studio",
  "How to create a home photography studio",
  "How to create a home craft or sewing room",
  "A beginner's guide to real estate investing",
  "A step-by-step guide to buying your first home",
  "A guide to understanding the mortgage process",
  "A guide to home inspections and what to look for",
  "A guide to understanding property taxes",
  "A guide to the different types of mortgages",
  "A guide to the home buying process for veterans",
  "A guide to understanding home insurance",
  "A guide to home staging for sellers",
  "A guide to understanding property values and appraisals",
  "A guide to understanding closing costs",
  "A guide to understanding zoning laws and building codes",
  "A guide to understanding the real estate market",
  "A guide to understanding real estate contracts",
  "A guide to understanding home warranties",
  "A guide to understanding home security systems",
  "A guide to understanding home automation systems",
  "A guide to understanding the benefits of owning a vacation home",
  "A guide to understanding property management",
  "A guide to understanding the benefits of renting vs. buying",
  "A guide to understanding real estate trends",
  "How to buy and sell luxury properties",
  "How to buy and sell homes for first-time home buyers",
  "How to buy and sell properties for investors",
  "How to buy and sell new construction properties",
  "How to buy and sell foreclosures",
  "How to buy and sell short sales",
  "How to buy and sell rental properties",
  "How to buy and sell vacation homes",
  "How to buy and sell waterfront properties",
  "How to buy and sell beach properties",
  "How to buy and sell ski properties",
  "How to buy and sell properties on golf courses",
  "How to buy and sell farm and ranch properties",
  "How to buy and sell commercial properties",
  "Why use a real estate agent instead of going FSBO?",
  "What does 'under contract' really mean?",
  "The steps to buying your first home",
  "The importance of getting pre-approved",
  "How to win in a multiple offer situation",
  "What is earnest money and how does it work?",
  "The difference between being pre-qualified and pre-approved",\
  "How\
