import { type NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  try {
    console.log("Starting simple PDF generation...")

    const formData = await request.formData()
    const analysis = formData.get("analysis") as string
    const agentName = formData.get("agentName") as string
    const propertyAddress = formData.get("propertyAddress") as string

    console.log("PDF generation data received:", {
      analysisLength: analysis?.length,
      agentName,
      propertyAddress,
    })

    if (!analysis || !agentName) {
      console.error("Missing required fields for PDF generation")
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    // Create a simple text-based PDF content
    const pdfContent = `
REAL ESTATE CONTRACT ANALYSIS
========================================

Property Address: ${propertyAddress || "Not specified"}
Agent: ${agentName}
Generated: ${new Date().toLocaleDateString()}

ANALYSIS REPORT
========================================

${analysis}

========================================
Generated by RealDeal AI
${new Date().toISOString()}
    `.trim()

    // Convert to blob
    const blob = new Blob([pdfContent], { type: "text/plain" })
    const buffer = await blob.arrayBuffer()

    console.log("Simple text file generated, size:", buffer.byteLength)

    // Return as downloadable text file (since PDF generation is failing)
    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="Contract_Analysis_${
          propertyAddress?.replace(/[^a-z0-9]/gi, "_") || "Report"
        }.txt"`,
      },
    })
  } catch (error) {
    console.error("PDF generation error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
      error,
    })

    return NextResponse.json(
      {
        error: "Failed to generate PDF",
        details: error instanceof Error ? error.message : "Unknown error occurred",
      },
      { status: 500 },
    )
  }
}
