import { type NextRequest, NextResponse } from "next/server"
import puppeteer from "puppeteer"

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const analysis = formData.get("analysis") as string
    const agentName = formData.get("agentName") as string
    const propertyAddress = formData.get("propertyAddress") as string

    if (!analysis || !agentName) {
      return NextResponse.json({ error: "Missing required data" }, { status: 400 })
    }

    console.log("Generating PDF for contract analysis...")

    // Process the text to remove markdown and format for HTML
    const processedText = analysis
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .split("\n")
      .map((line) => {
        if (line.trim() === "") return "<br/>"
        if (line.startsWith("**") && line.endsWith("**")) {
          return `<h3 style="color: #D97706; margin-top: 20px; margin-bottom: 10px;">${line.replace(/\*\*/g, "")}</h3>`
        }
        if (line.startsWith("- ")) {
          return `<li style="margin-bottom: 5px;">${line.substring(2)}</li>`
        }
        return `<p style="margin-bottom: 10px;">${line}</p>`
      })
      .join("")

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>Contract Analysis - ${propertyAddress}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
              padding-bottom: 20px;
              border-bottom: 3px solid #D97706;
            }
            .logo {
              font-size: 24px;
              font-weight: bold;
              color: #D97706;
              margin-bottom: 10px;
            }
            .title {
              font-size: 28px;
              font-weight: bold;
              color: #1F2937;
              margin-bottom: 8px;
            }
            .subtitle {
              font-size: 16px;
              color: #6B7280;
              margin-bottom: 5px;
            }
            .content {
              margin-top: 30px;
            }
            .footer {
              margin-top: 50px;
              padding-top: 20px;
              border-top: 1px solid #E5E7EB;
              font-size: 12px;
              color: #9CA3AF;
              text-align: center;
            }
            ul {
              margin: 15px 0;
              padding-left: 20px;
            }
            li {
              margin-bottom: 8px;
            }
            h3 {
              color: #D97706;
              font-size: 18px;
              margin-top: 25px;
              margin-bottom: 15px;
              padding-bottom: 5px;
              border-bottom: 1px solid #E5E7EB;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">The Next Level U Portal</div>
            <div class="title">Real Estate Contract Analysis</div>
            <div class="subtitle">${propertyAddress}</div>
            <div class="subtitle">Prepared for: ${agentName}</div>
            <div class="subtitle">Generated on: ${new Date().toLocaleDateString()}</div>
          </div>
          
          <div class="content">
            ${processedText}
          </div>
          
          <div class="footer">
            <p>This analysis was generated by RealDeal AI | The Next Level U Portal</p>
            <p>For educational and informational purposes only. Please consult with a qualified real estate attorney for legal advice.</p>
          </div>
        </body>
      </html>
    `

    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
    })

    const page = await browser.newPage()
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "20mm",
        right: "20mm",
        bottom: "20mm",
        left: "20mm",
      },
    })

    await browser.close()

    return new NextResponse(pdf, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Contract_Analysis_${propertyAddress.replace(/[^a-z0-9]/gi, "_")}.pdf"`,
      },
    })
  } catch (error) {
    console.error("Error generating PDF:", error)
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 })
  }
}
