import type { TenantConfig } from "../types"

export const century21CanadaConfig: TenantConfig = {
  id: "century21-canada",
  name: "Century 21 Canada",
  domain: "century21canada.thenextlevelu.com",
  logo: "/images/tenants/century21-canada-logo.png",
  primaryColor: "#b6a888",
  secondaryColor: "#a39577",
  features: {
    aiHub: true,
    prospectingHub: true,
    marketingHub: true,
    trainingHub: true,
    networkingHub: true,
    servicesHub: true,
    creationsDashboard: true,
    analytics: false,
    customHomePage: null,
    whiteLabel: true,
    customBranding: true,
    multiLanguage: false,
    ssoIntegration: false,
    customDomain: true,
    apiAccess: false,
    advancedAnalytics: false,
    prioritySupport: true,
    customIntegrations: false,
    bulkOperations: false,
    teamManagement: false,
    roleBasedAccess: false,
    auditLogs: false,
    dataExport: true,
    customReporting: false,
    webhooks: false,
    rateLimiting: false,
    ipWhitelisting: false,
    singleSignOn: false,
    ldapIntegration: false,
    samlIntegration: false,
    mfaRequired: false,
    passwordPolicy: false,
    sessionManagement: false,
    encryptionAtRest: true,
    encryptionInTransit: true,
    gdprCompliance: true,
    hipaaCompliance: false,
    soc2Compliance: false,
    backupRetention: 30,
    disasterRecovery: false,
    uptimeSla: 99.9,
    supportTier: "premium",
    onboarding: true,
    training: true,
    customization: true,
    migration: false,
    consulting: false,
  },
  branding: {
    companyName: "Century 21 Canada",
    tagline: "Your Real Estate Success Partner",
    description: "Empowering Century 21 Canada agents with cutting-edge AI tools and comprehensive training.",
    contactEmail: "support@century21canada.thenextlevelu.com",
    supportPhone: "+1-800-CENTURY",
    website: "https://century21.ca",
    socialMedia: {
      facebook: "https://facebook.com/century21canada",
      twitter: "https://twitter.com/century21canada",
      linkedin: "https://linkedin.com/company/century21canada",
      instagram: "https://instagram.com/century21canada",
    },
  },
  customization: {
    hideDefaultBranding: true,
    customFooter: true,
    customHeader: true,
    customSidebar: false,
    customTheme: true,
    customFonts: false,
    customColors: true,
    customLayout: false,
  },
  integrations: {
    crm: [],
    mls: [],
    email: [],
    calendar: [],
    storage: [],
    analytics: [],
    payment: [],
    communication: [],
    marketing: [],
    social: [],
  },
  limits: {
    users: 1000,
    storage: 100, // GB
    apiCalls: 10000, // per month
    exports: 50, // per month
    customReports: 10,
    webhooks: 5,
    integrations: 10,
  },
  billing: {
    plan: "enterprise",
    pricePerUser: 0, // Custom pricing
    billingCycle: "annual",
    trialDays: 0,
    setupFee: 0,
    customPricing: true,
  },
}
