import { type NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const { formData, businessPlan } = await request.json()

    if (!formData || !businessPlan || !formData.email) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    const { data, error } = await resend.emails.send({
      from: "The Next Level U <noreply@marketing.thenextlevelu.com>",
      to: [formData.email],
      subject: `Your 90-Day Business Plan - ${formData.name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; background: #f8fafc;">
          <div style="background: linear-gradient(135deg, #10B981, #059669); padding: 40px 30px; text-align: center; color: white;">
            <h1 style="margin: 0; font-size: 32px; font-weight: bold;">90-DAY BUSINESS PLAN</h1>
            <p style="margin: 10px 0 0 0; font-size: 18px; opacity: 0.9;">
              Generated by BizPlan AI - The Next Level U
            </p>
            <p style="margin: 5px 0 0 0; font-size: 16px; opacity: 0.8;">
              Agent: ${formData.name}
            </p>
          </div>
          
          <div style="padding: 40px 30px; background: white;">
            <div style="margin-bottom: 30px;">
              <h2 style="color: #1e40af; font-size: 24px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                🎯 FINANCIAL GOALS
              </h2>
              <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #0ea5e9;">
                <p style="margin: 0; color: #0c4a6e;"><strong>Target Earnings (90 days):</strong> $${formData.targetEarnings.toLocaleString()}</p>
                <p style="margin: 8px 0 0 0; color: #0c4a6e;"><strong>Money Plan:</strong> ${formData.moneyPlan}</p>
                <p style="margin: 8px 0 0 0; color: #0c4a6e;"><strong>Average Commission:</strong> $${formData.avgCommission.toLocaleString()}</p>
                <p style="margin: 8px 0 0 0; color: #0c4a6e;"><strong>Conversion Rate:</strong> ${formData.conversionRate}%</p>
              </div>
            </div>

            <div style="margin-bottom: 30px;">
              <h2 style="color: #1e40af; font-size: 24px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                📊 KEY METRICS
              </h2>
              <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px;">
                <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; text-align: center; border: 1px solid #bbf7d0;">
                  <div style="font-size: 28px; font-weight: bold; color: #15803d;">${businessPlan.dealsNeeded}</div>
                  <div style="color: #166534; font-size: 14px;">Deals Needed</div>
                </div>
                <div style="background: #eff6ff; padding: 20px; border-radius: 8px; text-align: center; border: 1px solid #bfdbfe;">
                  <div style="font-size: 28px; font-weight: bold; color: #1d4ed8;">${businessPlan.appointmentsNeeded}</div>
                  <div style="color: #1e40af; font-size: 14px;">Appointments Needed</div>
                </div>
                <div style="background: #fff7ed; padding: 20px; border-radius: 8px; text-align: center; border: 1px solid #fed7aa;">
                  <div style="font-size: 28px; font-weight: bold; color: #c2410c;">${businessPlan.conversationsNeeded}</div>
                  <div style="color: #ea580c; font-size: 14px;">Conversations Needed</div>
                </div>
                <div style="background: #faf5ff; padding: 20px; border-radius: 8px; text-align: center; border: 1px solid #e9d5ff;">
                  <div style="font-size: 28px; font-weight: bold; color: #9333ea;">${businessPlan.attemptsNeeded}</div>
                  <div style="color: #7c3aed; font-size: 14px;">Total Attempts Needed</div>
                </div>
              </div>
            </div>

            <div style="margin-bottom: 30px;">
              <h2 style="color: #1e40af; font-size: 24px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                📅 DAILY ACTIVITY TARGETS
              </h2>
              <div style="background: #f8fafc; padding: 25px; border-radius: 8px; border: 1px solid #e2e8f0;">
                <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; text-align: center;">
                  <div>
                    <div style="font-size: 24px; font-weight: bold; color: #374151;">${businessPlan.dailyAttempts}</div>
                    <div style="color: #6b7280; font-size: 14px;">Attempts per day</div>
                  </div>
                  <div>
                    <div style="font-size: 24px; font-weight: bold; color: #374151;">${businessPlan.dailyConversations}</div>
                    <div style="color: #6b7280; font-size: 14px;">Conversations per day</div>
                  </div>
                  <div>
                    <div style="font-size: 24px; font-weight: bold; color: #374151;">${businessPlan.dailyAppointments}</div>
                    <div style="color: #6b7280; font-size: 14px;">Appointments per day</div>
                  </div>
                </div>
              </div>
            </div>

            <div style="margin-bottom: 30px;">
              <h2 style="color: #1e40af; font-size: 24px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                🔢 CALCULATION BREAKDOWN
              </h2>
              <div style="background: #f9fafb; padding: 20px; border-radius: 8px;">
                <ul style="color: #374151; line-height: 1.8; margin: 0; padding-left: 20px;">
                  <li>To earn $${formData.targetEarnings.toLocaleString()}, you need <strong>${businessPlan.dealsNeeded} deals</strong></li>
                  <li>To get ${businessPlan.dealsNeeded} deals, you need <strong>${businessPlan.appointmentsNeeded} appointments</strong></li>
                  <li>To get ${businessPlan.appointmentsNeeded} appointments, you need <strong>${businessPlan.conversationsNeeded} conversations</strong></li>
                  <li>To get ${businessPlan.conversationsNeeded} conversations, you need <strong>${businessPlan.attemptsNeeded} total attempts</strong></li>
                </ul>
              </div>
            </div>

            <div style="background: #10b981; color: white; padding: 25px; border-radius: 8px; margin-bottom: 30px;">
              <h3 style="margin: 0 0 15px 0; font-size: 20px;">🎯 SUCCESS TIPS</h3>
              <ul style="margin: 0; padding-left: 20px; line-height: 1.7;">
                <li>Remember: It takes an average of 7 attempts to get one meaningful conversation</li>
                <li>Track your daily attempts and conversations to stay on target</li>
                <li>Focus on quality conversations that lead to appointments</li>
                <li>Follow up consistently - most deals happen after multiple touchpoints</li>
                <li>Adjust your approach if conversion rates are lower than expected</li>
              </ul>
            </div>
          </div>
          
          <div style="background: #1f2937; padding: 30px; text-align: center; color: white;">
            <p style="margin: 0; font-size: 16px; font-weight: 600;">The Next Level U - BizPlan AI</p>
            <p style="margin: 8px 0 0 0; font-size: 14px; opacity: 0.8;">
              Generated on ${new Date().toLocaleDateString()}
            </p>
          </div>
        </div>
      `,
    })

    if (error) {
      console.error("Resend error:", error)
      return NextResponse.json({ error: "Failed to send email" }, { status: 500 })
    }

    return NextResponse.json({ success: true, data })
  } catch (error) {
    console.error("Email sending error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
