"use server"

import { generateText } from "ai"
import { openai } from "@ai-sdk/openai"

type ListingFormData = {
  propertyAddress: string
  listingPrice: string
  bedrooms: string
  bathrooms: string
  squareFootage: string
  feature1: string
  feature2: string
  feature3: string
  feature4: string
  feature5: string
  agentName: string
  agentEmail: string
}

export async function generateListingDescription(formData: ListingFormData) {
  try {
    const prompt = `Take on the role of a seasoned real estate copywriter and marketing expert. Write an emotionally compelling, professionally polished, and sensory-rich listing description for a home located at ${formData.propertyAddress}, listed for ${formData.listingPrice}.

Highlight the following key features in a natural, engaging flow:

Feature 1: ${formData.feature1}
Feature 2: ${formData.feature2}
Feature 3: ${formData.feature3}
Feature 4: ${formData.feature4}
Feature 5: ${formData.feature5}

Bedrooms: ${formData.bedrooms}
Bathrooms: ${formData.bathrooms}
Square Footage: ${formData.squareFootage}

Writing Guidelines:
Use Visual Language: Words like see, picture, stunning, view, design, bright, sun-drenched, open-concept
Use Auditory Language: Words like quiet, peaceful, echoes of laughter, welcoming tone, soothing
Use Kinesthetic Language: Words like feel, warm, cozy, inviting, flow, spacious, touch

Make the reader see the lifestyle, hear the peace or excitement, and feel the comfort and charm of living in this home.

Avoid robotic or cliché phrases. Keep it unique, story-driven, and emotionally resonant. The goal is to help potential buyers instantly imagine themselves living there and inspire them to take the next step.

End the description with a strong, inviting call to action that encourages scheduling a private showing or reaching out for more information.`

    const { text: generatedDescription } = await generateText({
      model: openai("gpt-4o"),
      prompt,
    })

    return {
      description: generatedDescription,
    }
  } catch (error) {
    console.error("Error generating listing description:", error)
    throw new Error("Failed to generate listing description. Please try again.")
  }
}

export async function generateListingHTML(formData: ListingFormData, description: string) {
  // Create HTML content for email attachment
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Property Listing: ${formData.propertyAddress}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          background: #b6a888;
          color: white;
          padding: 30px;
          text-align: center;
          margin-bottom: 30px;
          border-radius: 8px;
        }
        .header h1 {
          margin: 0;
          font-size: 28px;
        }
        .header p {
          margin: 10px 0 0;
          font-size: 16px;
        }
        .property-title {
          font-size: 24px;
          font-weight: bold;
          margin-bottom: 5px;
          color: #1f2937;
        }
        .property-price {
          font-size: 22px;
          color: #b6a888;
          margin-bottom: 20px;
          font-weight: bold;
        }
        .divider {
          border-top: 1px solid #e5e7eb;
          margin: 20px 0;
        }
        .description {
          font-size: 16px;
          line-height: 1.8;
          margin-bottom: 30px;
          color: #374151;
        }
        .details-title {
          font-size: 14px;
          font-weight: bold;
          color: #6b7280;
          margin-bottom: 10px;
          text-transform: uppercase;
        }
        .details {
          font-size: 14px;
          color: #4b5563;
          margin-bottom: 5px;
        }
        .footer {
          background: #f9fafb;
          border-top: 1px solid #e5e7eb;
          padding: 20px;
          text-align: center;
          font-size: 12px;
          color: #6b7280;
          margin-top: 40px;
          border-radius: 8px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Property Listing</h1>
        <p>Generated by ListIT - The Next Level U</p>
      </div>
      
      <div class="property-title">${formData.propertyAddress}</div>
      <div class="property-price">${formData.listingPrice}</div>
      
      <div class="divider"></div>
      
      <div class="description">
        ${description.replace(/\n/g, "<br>")}
      </div>
      
      <div class="details-title">PROPERTY DETAILS</div>
      <div class="details"><strong>Bedrooms:</strong> ${formData.bedrooms}</div>
      <div class="details"><strong>Bathrooms:</strong> ${formData.bathrooms}</div>
      <div class="details"><strong>Square Footage:</strong> ${formData.squareFootage}</div>
      
      <div class="divider"></div>
      
      <div class="details-title">KEY FEATURES</div>
      <div class="details">• ${formData.feature1}</div>
      <div class="details">• ${formData.feature2}</div>
      <div class="details">• ${formData.feature3}</div>
      <div class="details">• ${formData.feature4}</div>
      <div class="details">• ${formData.feature5}</div>
      
      <div class="footer">
        <p>© 2024 The Next Level U - Empowering Real Estate Professionals</p>
        <p>Generated with AI-powered tools designed for real estate success</p>
      </div>
    </body>
    </html>
  `

  return html
}
