import { type NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const { action, data } = await request.json()

    if (action === "send-email") {
      return await sendEmail(data)
    } else {
      return NextResponse.json({ error: "Invalid action" }, { status: 400 })
    }
  } catch (error) {
    console.error("Error in IdeaHub API:", error)
    return NextResponse.json({ error: error instanceof Error ? error.message : "Unknown error" }, { status: 500 })
  }
}

async function sendEmail(data: { to: string; name: string; content: string; imageUrl: string }) {
  try {
    console.log("Sending IdeaHub email via Resend to:", data.to)

    // Convert base64 image to buffer for email attachment
    let imageBuffer: Buffer | null = null
    try {
      if (data.imageUrl && data.imageUrl.startsWith("data:image")) {
        // Extract base64 data
        const base64Data = data.imageUrl.split(",")[1]
        imageBuffer = Buffer.from(base64Data, "base64")
      }
    } catch (imageError) {
      console.warn("Could not process image for attachment:", imageError)
    }

    const response = await resend.emails.send({
      from: "IdeaHub AI - The Next Level U <noreply@marketing.thenextlevelu.com>",
      to: [data.to],
      subject: "Your AI-Generated Social Media Content - The Next Level U",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #7c3aed, #2563eb); padding: 20px; text-align: center;">
            <h1 style="color: white; margin: 0;">Your Content is Ready!</h1>
            <p style="color: white; margin: 10px 0 0 0;">Generated by IdeaHub AI - The Next Level U</p>
          </div>
          
          <div style="padding: 30px; background: #f9fafb;">
            <h2 style="color: #1f2937; margin-bottom: 20px;">Hi ${data.name},</h2>
            
            <p style="color: #4b5563; line-height: 1.6;">
              Your AI-generated social media content is ready! Here's your professional post content and accompanying image with Century 21 branding.
            </p>
            
            <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #7c3aed;">
              <h3 style="color: #1f2937; margin-top: 0;">Your Social Media Post:</h3>
              <p style="color: #4b5563; line-height: 1.6; white-space: pre-wrap;">${data.content}</p>
            </div>
            
            <p style="color: #4b5563; line-height: 1.6;">
              ${imageBuffer ? "The accompanying branded image is attached to this email." : "You can also download the image from the website."} You can use both the text and image for your social media posts on Facebook, LinkedIn, Instagram, and other platforms.
            </p>
            
            <p style="color: #6b7280; font-size: 14px; line-height: 1.6;">
              Best regards,<br>
              The Next Level U Team<br>
              <a href="mailto:MikePuma@c21be.com" style="color: #7c3aed;">MikePuma@c21be.com</a>
            </p>
          </div>
          
          <div style="background: #1f2937; padding: 20px; text-align: center;">
            <p style="color: #9ca3af; margin: 0; font-size: 14px;">
              © 2024 The Next Level U. Empowering real estate professionals with AI-powered tools.
            </p>
          </div>
        </div>
      `,
      attachments: imageBuffer
        ? [
            {
              filename: "social-media-image-branded.jpg",
              content: imageBuffer,
              contentType: "image/jpeg",
            },
          ]
        : [],
    })

    if (response.error) {
      console.error("Resend error:", response.error)
      throw new Error(`Failed to send email: ${response.error.message}`)
    }

    console.log("IdeaHub email sent successfully:", response.data?.id)
    return NextResponse.json({ success: true, messageId: response.data?.id })
  } catch (error) {
    console.error("Error sending IdeaHub email:", error)
    throw new Error(`Failed to send email: ${error instanceof Error ? error.message : "Unknown error"}`)
  }
}
