import { NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req) {
  try {
    const body = await req.json()
    const { agentName, propertyAddress, analysis, to } = body

    const emailHtml = `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8">
    <title>Contract Analysis - ${propertyAddress || "Property"}</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
      }
      .header {
        background: linear-gradient(135deg, #D97706, #F59E0B);
        color: white;
        padding: 30px;
        text-align: center;
        margin-bottom: 30px;
        border-radius: 8px;
      }
      .header h1 {
        margin: 0;
        font-size: 28px;
      }
      .header p {
        margin: 10px 0 0;
        font-size: 16px;
        opacity: 0.9;
      }
      .property-info {
        background: #F3F4F6;
        padding: 20px;
        border-radius: 8px;
        margin-bottom: 30px;
        border-left: 4px solid #D97706;
      }
      .property-info h2 {
        margin: 0 0 10px 0;
        color: #1F2937;
        font-size: 20px;
      }
      .property-info p {
        margin: 5px 0;
        color: #4B5563;
      }
      .analysis-content {
        background: white;
        border: 1px solid #E5E7EB;
        border-radius: 8px;
        padding: 25px;
        margin-bottom: 30px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      }
      .analysis-content h3 {
        color: #D97706;
        margin-top: 0;
        margin-bottom: 15px;
        font-size: 18px;
      }
      .analysis-text {
        white-space: pre-wrap;
        font-size: 14px;
        line-height: 1.7;
        color: #374151;
      }
      .footer {
        background: #1F2937;
        color: #9CA3AF;
        padding: 20px;
        text-align: center;
        border-radius: 8px;
        font-size: 12px;
      }
      .footer p {
        margin: 5px 0;
      }
      .disclaimer {
        background: #FEF3C7;
        border: 1px solid #F59E0B;
        border-radius: 8px;
        padding: 15px;
        margin: 20px 0;
        font-size: 12px;
        color: #92400E;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>Contract Analysis Complete</h1>
      <p>Generated by RealDeal AI - The Next Level U Portal</p>
    </div>
    
    <div class="property-info">
      <h2>Property Information</h2>
      <p><strong>Agent:</strong> ${agentName}</p>
      <p><strong>Property Address:</strong> ${propertyAddress || "Not specified"}</p>
      <p><strong>Analysis Date:</strong> ${new Date().toLocaleDateString()}</p>
    </div>
    
    <div class="analysis-content">
      <h3>📋 Contract Analysis Summary</h3>
      <div class="analysis-text">${analysis}</div>
    </div>
    
    <div class="disclaimer">
      <p><strong>⚠️ Important Disclaimer:</strong> This analysis is generated by AI and is for informational purposes only. Please consult with a qualified real estate attorney for legal advice and verification of all contract terms and conditions.</p>
    </div>
    
    <div class="footer">
      <p><strong>RealDeal AI</strong> - The Next Level U Portal</p>
      <p>Empowering Real Estate Professionals with AI-powered Contract Analysis</p>
      <p>© 2024 The Next Level U. All rights reserved.</p>
    </div>
  </body>
  </html>
`

    const data = await resend.emails.send({
      from: "Acme <onboarding@resend.dev>",
      to: [to],
      subject: "RealDeal AI Contract Analysis",
      html: emailHtml,
    })

    return NextResponse.json(data)
  } catch (error) {
    return NextResponse.json({ error })
  }
}
