import { type NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const analysis = formData.get("analysis") as string
    const agentName = formData.get("agentName") as string
    const propertyAddress = formData.get("propertyAddress") as string
    const email = formData.get("email") as string

    if (!analysis || !agentName || !email) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: "Email service not configured" }, { status: 500 })
    }

    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Contract Analysis</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .header { background: #f8f9fa; padding: 20px; text-align: center; }
          .content { padding: 20px; }
          .analysis { background: #f5f5f5; padding: 15px; margin: 20px 0; border-left: 4px solid #007bff; }
          .footer { background: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Contract Analysis Report</h1>
          <p><strong>Agent:</strong> ${agentName}</p>
          <p><strong>Property:</strong> ${propertyAddress || "Not specified"}</p>
        </div>
        <div class="content">
          <div class="analysis">
            <pre style="white-space: pre-wrap; font-family: inherit;">${analysis}</pre>
          </div>
        </div>
        <div class="footer">
          <p>Generated by RealDeal AI - The Next Level U Portal</p>
          <p>© ${new Date().getFullYear()} The Next Level U. All rights reserved.</p>
        </div>
      </body>
      </html>
    `

    const { data, error } = await resend.emails.send({
      from: "noreply@marketing.thenextlevelu.com",
      to: [email],
      subject: `Contract Analysis - ${propertyAddress || "Property Report"}`,
      html: emailHtml,
    })

    if (error) {
      console.error("Resend error:", error)
      return NextResponse.json({ error: "Failed to send email" }, { status: 500 })
    }

    return NextResponse.json({
      success: true,
      messageId: data?.id,
    })
  } catch (error) {
    console.error("Email sending error:", error)
    return NextResponse.json(
      {
        error: "Failed to send email",
        details: error instanceof Error ? error.message : "Unknown error occurred",
      },
      { status: 500 },
    )
  }
}
</merged_code>
