import { type NextRequest, NextResponse } from "next/server"
import nodemailer from "nodemailer"
import puppeteer from "puppeteer"

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const analysis = formData.get("analysis") as string
    const agentName = formData.get("agentName") as string
    const propertyAddress = formData.get("propertyAddress") as string
    const email = formData.get("email") as string

    if (!analysis || !agentName || !email) {
      return NextResponse.json({ error: "Missing required data" }, { status: 400 })
    }

    console.log("Generating PDF for email attachment...")

    // Process the text to remove markdown and format for HTML
    const processedText = analysis
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .split("\n")
      .map((line) => {
        if (line.trim() === "") return "<br/>"
        if (line.startsWith("**") && line.endsWith("**")) {
          return `<h3 style="color: #D97706; margin-top: 20px; margin-bottom: 10px;">${line.replace(/\*\*/g, "")}</h3>`
        }
        if (line.startsWith("- ")) {
          return `<li style="margin-bottom: 5px;">${line.substring(2)}</li>`
        }
        return `<p style="margin-bottom: 10px;">${line}</p>`
      })
      .join("")

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>Contract Analysis - ${propertyAddress}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
              padding-bottom: 20px;
              border-bottom: 3px solid #D97706;
            }
            .logo {
              font-size: 24px;
              font-weight: bold;
              color: #D97706;
              margin-bottom: 10px;
            }
            .title {
              font-size: 28px;
              font-weight: bold;
              color: #1F2937;
              margin-bottom: 8px;
            }
            .subtitle {
              font-size: 16px;
              color: #6B7280;
              margin-bottom: 5px;
            }
            .content {
              margin-top: 30px;
            }
            .footer {
              margin-top: 50px;
              padding-top: 20px;
              border-top: 1px solid #E5E7EB;
              font-size: 12px;
              color: #9CA3AF;
              text-align: center;
            }
            ul {
              margin: 15px 0;
              padding-left: 20px;
            }
            li {
              margin-bottom: 8px;
            }
            h3 {
              color: #D97706;
              font-size: 18px;
              margin-top: 25px;
              margin-bottom: 15px;
              padding-bottom: 5px;
              border-bottom: 1px solid #E5E7EB;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">The Next Level U Portal</div>
            <div class="title">Real Estate Contract Analysis</div>
            <div class="subtitle">${propertyAddress}</div>
            <div class="subtitle">Prepared for: ${agentName}</div>
            <div class="subtitle">Generated on: ${new Date().toLocaleDateString()}</div>
          </div>
          
          <div class="content">
            ${processedText}
          </div>
          
          <div class="footer">
            <p>This analysis was generated by RealDeal AI | The Next Level U Portal</p>
            <p>For educational and informational purposes only. Please consult with a qualified real estate attorney for legal advice.</p>
          </div>
        </body>
      </html>
    `

    // Generate PDF
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
    })

    const page = await browser.newPage()
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "20mm",
        right: "20mm",
        bottom: "20mm",
        left: "20mm",
      },
    })

    await browser.close()

    // Send email
    const transporter = nodemailer.createTransporter({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    })

    const mailOptions = {
      from: process.env.GMAIL_USER,
      to: email,
      subject: `Contract Analysis - ${propertyAddress}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #D97706; margin-bottom: 10px;">The Next Level U Portal</h1>
            <h2 style="color: #1F2937; margin-bottom: 5px;">Contract Analysis Complete</h2>
          </div>
          
          <div style="background: #F9FAFB; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <p style="margin: 0 0 10px 0;"><strong>Hello ${agentName},</strong></p>
            <p style="margin: 0 0 10px 0;">Your contract analysis for <strong>${propertyAddress}</strong> has been completed and is attached as a PDF.</p>
            <p style="margin: 0;">This comprehensive analysis includes key dates, financial details, and important considerations for your review.</p>
          </div>
          
          <div style="background: #FEF3C7; padding: 15px; border-radius: 8px; border-left: 4px solid #D97706; margin-bottom: 20px;">
            <p style="margin: 0; font-size: 14px; color: #92400E;">
              <strong>Important:</strong> This analysis is for informational purposes only. Please consult with a qualified real estate attorney for legal advice.
            </p>
          </div>
          
          <div style="text-align: center; margin-top: 30px;">
            <p style="font-size: 12px; color: #6B7280; margin: 0;">
              Generated by RealDeal AI | The Next Level U Portal<br>
              ${new Date().toLocaleDateString()}
            </p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: `Contract_Analysis_${propertyAddress.replace(/[^a-z0-9]/gi, "_")}.pdf`,
          content: pdf,
          contentType: "application/pdf",
        },
      ],
    }

    await transporter.sendMail(mailOptions)

    return NextResponse.json({ success: true, message: "Contract analysis sent successfully!" })
  } catch (error) {
    console.error("Error sending contract analysis email:", error)
    return NextResponse.json(
      {
        error: "Failed to send email",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}
